/*
 * Dtz Objectstore
 *
 * a generated client for the DTZ Objectstore API
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Stats200Response {
    #[serde(rename = "amountOfFiles", skip_serializing_if = "Option::is_none")]
    pub amount_of_files: Option<f64>,
    #[serde(rename = "amountOfStorage", skip_serializing_if = "Option::is_none")]
    pub amount_of_storage: Option<f64>,
}

impl Stats200Response {
    pub fn new() -> Stats200Response {
        Stats200Response {
            amount_of_files: None,
            amount_of_storage: None,
        }
    }
}


