/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 1.0.26
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */


pub static SVC_URL: &str = "https://identity.dtz.rocks/api/2021-02-21";
