/*
 * DTZ Billing Api
 *
 * a generated client for the DTZ Billing API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckFunded200Response {
    #[serde(rename = "isFunded", skip_serializing_if = "Option::is_none")]
    pub is_funded: Option<bool>,
}

impl CheckFunded200Response {
    pub fn new() -> CheckFunded200Response {
        CheckFunded200Response {
            is_funded: None,
        }
    }
}


