/*
 * DTZ Billing Api
 *
 * a generated client for the DTZ Billing API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStats200ResponsePreviousDay {
    #[serde(rename = "euro", skip_serializing_if = "Option::is_none")]
    pub euro: Option<f64>,
    #[serde(rename = "watt", skip_serializing_if = "Option::is_none")]
    pub watt: Option<f64>,
}

impl GetStats200ResponsePreviousDay {
    pub fn new() -> GetStats200ResponsePreviousDay {
        GetStats200ResponsePreviousDay {
            euro: None,
            watt: None,
        }
    }
}


