/*
 * DTZ Flows Api
 *
 * a generated client for the DTZ Flows API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rss2emailDiscoverPost200Response {
    #[serde(rename = "feedUrl", skip_serializing_if = "Option::is_none")]
    pub feed_url: Option<String>,
    #[serde(rename = "feedType", skip_serializing_if = "Option::is_none")]
    pub feed_type: Option<String>,
}

impl Rss2emailDiscoverPost200Response {
    pub fn new() -> Rss2emailDiscoverPost200Response {
        Rss2emailDiscoverPost200Response {
            feed_url: None,
            feed_type: None,
        }
    }
}


