/*
 * DTZ Container Registry
 *
 * a generated client for the DTZ Container Registry API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "repositories", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<Vec<String>>,
}

impl CatalogResponse {
    pub fn new() -> CatalogResponse {
        CatalogResponse {
            repositories: None,
        }
    }
}

