/*
 * DTZ Container Registry
 *
 * a generated client for the DTZ Container Registry API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManifestResponseSubjectPlatform {
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<String>,
}

impl ManifestResponseSubjectPlatform {
    pub fn new() -> ManifestResponseSubjectPlatform {
        ManifestResponseSubjectPlatform {
            architecture: None,
            os: None,
        }
    }
}

