/*
 * DTZ Container Registry
 *
 * a generated client for the DTZ Container Registry API
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponse {
    #[serde(rename = "imageCount", skip_serializing_if = "Option::is_none")]
    pub image_count: Option<i32>,
    #[serde(rename = "serverUrl", skip_serializing_if = "Option::is_none")]
    pub server_url: Option<String>,
}

impl StatsResponse {
    pub fn new() -> StatsResponse {
        StatsResponse {
            image_count: None,
            server_url: None,
        }
    }
}


