/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 1.0.26
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbstractRole {
    #[serde(rename = "roleId")]
    pub role_id: dtz_identifier::RoleId,
    #[serde(rename = "roleAlias", skip_serializing_if = "Option::is_none")]
    pub role_alias: Option<String>,
    #[serde(rename = "roleScope")]
    pub role_scope: String,
}

impl AbstractRole {
    pub fn new(role_id: dtz_identifier::RoleId, role_scope: String) -> AbstractRole {
        AbstractRole {
            role_id,
            role_alias: None,
            role_scope,
        }
    }
}

