/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbstractRole {
    #[serde(rename = "roleId", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<dtz_identifier::RoleId>,
    #[serde(rename = "roleAlias", skip_serializing_if = "Option::is_none")]
    pub role_alias: Option<String>,
    #[serde(rename = "roleScope", skip_serializing_if = "Option::is_none")]
    pub role_scope: Option<String>,
}

impl AbstractRole {
    pub fn new() -> AbstractRole {
        AbstractRole {
            role_id: None,
            role_alias: None,
            role_scope: None,
        }
    }
}


