/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssumeIdentityByEmail {
    #[serde(rename = "email")]
    pub email: String,
}

impl AssumeIdentityByEmail {
    pub fn new(email: String) -> AssumeIdentityByEmail {
        AssumeIdentityByEmail {
            email,
        }
    }
}


