/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthResponse {
    #[serde(rename = "token")]
    pub token: String,
}

impl AuthResponse {
    pub fn new(token: String) -> AuthResponse {
        AuthResponse {
            token,
        }
    }
}


