/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeAuthenticationRequest {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "oldPassword", skip_serializing_if = "Option::is_none")]
    pub old_password: Option<String>,
    #[serde(rename = "newPassword", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
}

impl ChangeAuthenticationRequest {
    pub fn new() -> ChangeAuthenticationRequest {
        ChangeAuthenticationRequest {
            email: None,
            old_password: None,
            new_password: None,
        }
    }
}

