/*
 * DTZ Identity
 *
 * a generated client for the DTZ Identity API
 *
 * The version of the OpenAPI document: 1.0.9
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewContextRequest {
    #[serde(rename = "identity_id", skip_serializing_if = "Option::is_none")]
    pub identity_id: Option<dtz_identifier::IdentityId>,
    #[serde(rename = "service_principal_id", skip_serializing_if = "Option::is_none")]
    pub service_principal_id: Option<dtz_identifier::IdentityId>,
}

impl NewContextRequest {
    pub fn new() -> NewContextRequest {
        NewContextRequest {
            identity_id: None,
            service_principal_id: None,
        }
    }
}


