/*
 * DTZ Observability
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogPushPostRequestInnerLinksInner {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl LogPushPostRequestInnerLinksInner {
    pub fn new() -> LogPushPostRequestInnerLinksInner {
        LogPushPostRequestInnerLinksInner {
            alias: None,
            url: None,
        }
    }
}


