/*
 * DTZ Observability
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogActivityGet200ResponseInner {
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl LogActivityGet200ResponseInner {
    pub fn new() -> LogActivityGet200ResponseInner {
        LogActivityGet200ResponseInner {
            ts: None,
            count: None,
        }
    }
}


