/*
 * DTZ Observability
 *
 * a generated client for the DTZ Observability API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMetricMetadata200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl GetMetricMetadata200Response {
    pub fn new() -> GetMetricMetadata200Response {
        GetMetricMetadata200Response {
            status: None,
            data: None,
        }
    }
}


