/*
 * DTZ Observability
 *
 * a generated client for the DTZ Observability API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryLogsRequest {
    #[serde(rename = "search", skip_serializing_if = "Option::is_none")]
    pub search: Option<String>,
}

impl QueryLogsRequest {
    pub fn new() -> QueryLogsRequest {
        QueryLogsRequest {
            search: None,
        }
    }
}

