/*
 * DTZ RSS2Email Api
 *
 * a generated client for the DTZ RSS2Email API
 *
 * The version of the OpenAPI document: 1.0.9
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoverFeedRequest {
    #[serde(rename = "url")]
    pub url: String,
}

impl DiscoverFeedRequest {
    pub fn new(url: String) -> DiscoverFeedRequest {
        DiscoverFeedRequest {
            url,
        }
    }
}

