/*
 * DTZ RSS2Email Api
 *
 * a generated client for the DTZ RSS2Email API
 *
 * The version of the OpenAPI document: 1.0.7
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedStatistics {
    #[serde(rename = "amountOfFeeds")]
    pub amount_of_feeds: i64,
    #[serde(rename = "amountOfNotificationDay")]
    pub amount_of_notification_day: i64,
    #[serde(rename = "amountOfNotificationWeek")]
    pub amount_of_notification_week: i64,
    #[serde(rename = "amountOfNotificationMonth")]
    pub amount_of_notification_month: i64,
}

impl FeedStatistics {
    pub fn new(amount_of_feeds: i64, amount_of_notification_day: i64, amount_of_notification_week: i64, amount_of_notification_month: i64) -> FeedStatistics {
        FeedStatistics {
            amount_of_feeds,
            amount_of_notification_day,
            amount_of_notification_week,
            amount_of_notification_month,
        }
    }
}


