/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateJobEnvVariablesValue {
    String(String),
    EncryptedValue(Box<models::EncryptedValue>),
    PlainValue(Box<models::PlainValue>),
}

impl Default for CreateJobEnvVariablesValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

