/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDomain {
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateDomain {
    pub fn new(name: String) -> CreateDomain {
        CreateDomain {
            name,
        }
    }
}


