/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Domain {
    #[serde(rename = "contextId")]
    pub context_id: dtz_identifier::ContextId,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "created")]
    pub created: String,
}

impl Domain {
    pub fn new(context_id: dtz_identifier::ContextId, name: String, verified: bool, created: String) -> Domain {
        Domain {
            context_id,
            name,
            verified,
            created,
        }
    }
}

