/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * The version of the OpenAPI document: 1.1.6
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JobResponseEnvVariablesValue {
    String(String),
    EncryptedValue(Box<models::EncryptedValue>),
}

impl Default for JobResponseEnvVariablesValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

