/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlainValue {
    /// the plain text value for server side encryption
    #[serde(rename = "plainValue", skip_serializing_if = "Option::is_none")]
    pub plain_value: Option<String>,
}

impl PlainValue {
    pub fn new() -> PlainValue {
        PlainValue {
            plain_value: None,
        }
    }
}


