/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

/// ServiceRewrite : provids url rewriting capabilities
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceRewrite {
    /// regex to match the incoming uri
    #[serde(rename = "source")]
    pub source: String,
    /// replacement value
    #[serde(rename = "target")]
    pub target: String,
}

impl ServiceRewrite {
    /// provids url rewriting capabilities
    pub fn new(source: String, target: String) -> ServiceRewrite {
        ServiceRewrite {
            source,
            target,
        }
    }
}

