/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateHostingRequestDomainsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "routing", skip_serializing_if = "Option::is_none")]
    pub routing: Option<Vec<crate::models::UpdateHostingRequestDomainsInnerRoutingInner>>,
}

impl UpdateHostingRequestDomainsInner {
    pub fn new() -> UpdateHostingRequestDomainsInner {
        UpdateHostingRequestDomainsInner {
            name: None,
            routing: None,
        }
    }
}


