/*
 * DTZ Containers
 *
 * a generated client for the DTZ Containers API
 *
 * The version of the OpenAPI document: 1.1.6
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateServiceRequestRewrite : provids url rewriting capabilities
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateServiceRequestRewrite {
    /// regex to match the incoming uri
    #[serde(rename = "source")]
    pub source: String,
    /// replacement value
    #[serde(rename = "target")]
    pub target: String,
}

impl UpdateServiceRequestRewrite {
    /// provids url rewriting capabilities
    pub fn new(source: String, target: String) -> UpdateServiceRequestRewrite {
        UpdateServiceRequestRewrite {
            source,
            target,
        }
    }
}

