/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatPrivileges {
    #[serde(rename = "allContextMembers", skip_serializing_if = "Option::is_none")]
    pub all_context_members: Option<bool>,
    #[serde(rename = "nullBot", skip_serializing_if = "Option::is_none")]
    pub null_bot: Option<String>,
    #[serde(rename = "supportEmployee", skip_serializing_if = "Option::is_none")]
    pub support_employee: Option<String>,
}

impl ChatPrivileges {
    pub fn new() -> ChatPrivileges {
        ChatPrivileges {
            all_context_members: None,
            null_bot: None,
            support_employee: None,
        }
    }
}

