/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chat {
    #[serde(rename = "chatId", skip_serializing_if = "Option::is_none")]
    pub chat_id: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<dtz_identifier::IdentityId>,
    #[serde(rename = "privileges", skip_serializing_if = "Option::is_none")]
    pub privileges: Option<Box<models::ChatPrivileges>>,
    #[serde(rename = "timeline", skip_serializing_if = "Option::is_none")]
    pub timeline: Option<Vec<models::ChatTimelineInner>>,
}

impl Chat {
    pub fn new() -> Chat {
        Chat {
            chat_id: None,
            created: None,
            owner: None,
            privileges: None,
            timeline: None,
        }
    }
}

