/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Container {
    #[serde(rename = "containerImage")]
    pub container_image: String,
    #[serde(rename = "containerIdentity", skip_serializing_if = "Option::is_none")]
    pub container_identity: Option<String>,
    #[serde(rename = "containerPullUser", skip_serializing_if = "Option::is_none")]
    pub container_pull_user: Option<String>,
    #[serde(rename = "containerPullPwd", skip_serializing_if = "Option::is_none")]
    pub container_pull_pwd: Option<String>,
    #[serde(rename = "envVariables", skip_serializing_if = "Option::is_none")]
    pub env_variables: Option<std::collections::HashMap<String, models::EnvironmentVariablesValue>>,
    #[serde(rename = "mounts", skip_serializing_if = "Option::is_none")]
    pub mounts: Option<Vec<models::ContainerMountsInner>>,
}

impl Container {
    pub fn new(container_image: String) -> Container {
        Container {
            container_image,
            container_identity: None,
            container_pull_user: None,
            container_pull_pwd: None,
            env_variables: None,
            mounts: None,
        }
    }
}

