/*
 * DTZ Core Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateJobRequestJobDefinition {
    #[serde(rename = "containerImage")]
    pub container_image: String,
    #[serde(rename = "containerTag", skip_serializing_if = "Option::is_none")]
    pub container_tag: Option<String>,
    #[serde(rename = "containerPullUser", skip_serializing_if = "Option::is_none")]
    pub container_pull_user: Option<String>,
    #[serde(rename = "containerPullPwd", skip_serializing_if = "Option::is_none")]
    pub container_pull_pwd: Option<String>,
}

impl CreateJobRequestJobDefinition {
    pub fn new(container_image: String) -> CreateJobRequestJobDefinition {
        CreateJobRequestJobDefinition {
            container_image,
            container_tag: None,
            container_pull_user: None,
            container_pull_pwd: None,
        }
    }
}


