/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllContext200ResponseContextsInner {
    #[serde(rename = "context_id", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<uuid::Uuid>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
}

impl GetAllContext200ResponseContextsInner {
    pub fn new() -> GetAllContext200ResponseContextsInner {
        GetAllContext200ResponseContextsInner {
            context_id: None,
            alias: None,
            created: None,
        }
    }
}


