/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused)]
use crate::models;




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngressResponse {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "pathPrefix")]
    pub path_prefix: String,
    /// owning scope, changes can only be performed within the scope
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(rename = "validity", skip_serializing_if = "Option::is_none")]
    pub validity: Option<Box<crate::models::Validity>>,
    #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
    pub login: Option<Box<crate::models::Login>>,
    #[serde(rename = "rewrite", skip_serializing_if = "Option::is_none")]
    pub rewrite: Option<Box<crate::models::Rewrite>>,
    #[serde(rename = "container", skip_serializing_if = "Option::is_none")]
    pub container: Option<Box<crate::models::Container>>,
    #[serde(rename = "staticContent", skip_serializing_if = "Option::is_none")]
    pub static_content: Option<Box<crate::models::StaticContent>>,
}

impl IngressResponse {
    pub fn new(domain: String, path_prefix: String) -> IngressResponse {
        IngressResponse {
            domain,
            path_prefix,
            scope: None,
            validity: None,
            login: None,
            rewrite: None,
            container: None,
            static_content: None,
        }
    }
}


