/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Login {
    #[serde(rename = "providerName")]
    pub provider_name: String,
}

impl Login {
    pub fn new(provider_name: String) -> Login {
        Login {
            provider_name,
        }
    }
}

