/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rewrite {
    /// URI source as Regex (re2 syntax)
    #[serde(rename = "source")]
    pub source: String,
    /// replacement string
    #[serde(rename = "target")]
    pub target: String,
}

impl Rewrite {
    pub fn new(source: String, target: String) -> Rewrite {
        Rewrite {
            source,
            target,
        }
    }
}

