/*
 * DTZ Core Api
 *
 * a generated client for the DTZ Core API
 *
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaticContent {
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    pub http: Option<Box<models::StaticContentHttp>>,
    #[serde(rename = "https", skip_serializing_if = "Option::is_none")]
    pub https: Option<Box<models::StaticContentHttp>>,
}

impl StaticContent {
    pub fn new() -> StaticContent {
        StaticContent {
            http: None,
            https: None,
        }
    }
}

