name: ci
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: cargo-bins/cargo-binstall@main
    - name: Install cargo-msrv
      run: cargo binstall cargo-msrv
    - name: Verify MSRV
      run: cargo msrv verify --path dtz
