name: ci
on:
  push:
jobs:
  ci:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install cargo-msrv
      run: cargo bininstall cargo-msrv
    - name: Verify MSRV
      run: cargo msrv verify
