/*
 * DTZ Container Registry
 *
 * a generated client for the DTZ Container Registry API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jens@apimeister.com
 * Generated by: https://openapi-generator.tech
 */


pub static SVC_URL: &str = "https://cr.dtz.rocks/api/2023-12-28";
